#!/bin/bash
echo “Введите параметр скрипта, который войдет в название каталога”
read number
user=”$(whoami)”
username=”$user”
mydir=”olympiad_”$username”_$number”
if  [ -d “$mydir” ]
then
    echo “$mydir директория уже существует”
else
    mkdir “olympiad_”$username”_$number”
    echo “$mydir директория не существовала и теперь создана”
fi
